SAMPLES = ["TLE66_N", "TLE66_T"]

rule all:
    input:
        "100.final/combined.snps.annotated.tsv",
        "150.db/snps.sqlite",
        "160.figures/fig1_impact_severity.svg",
        "160.figures/fig2_top_genes.svg"

rule fastqc:
    input:
        "{sample}.fastq"
    output: 
        "010.fastqc/{sample}_fastqc.html"
    shell:
        """ 
        fastqc {input} --outdir 010.fastqc/
        test -s {output}
        """

rule align:
    input:
        fastq="{sample}.fastq",
        ref="/lustre1/project/stg_00079/teaching/hg38_9/chr9.fa"
    output:
        "020.align/{sample}.bam"
    shell:
        """
        bwa mem -R "@RG\\tID:{wildcards.sample}\\tSM:{wildcards.sample}\\tLB:{wildcards.sample}\\tPL:ILLUMINA" {input.ref} {input.fastq} | samtools view -Sb - > {output}
        test -s {output}
        """

rule sort_index:
    input:
        "020.align/{sample}.bam"
    output:
        bam="030.sort/{sample}.sorted.bam",
        bai="030.sort/{sample}.sorted.bam.bai"
    shell:
        """
        samtools sort {input} -o {output.bam}
        samtools index {output.bam}
        test -s {output.bam}
        test -s {output.bai}
        """

rule call_variant:
    input:
        bams=expand("030.sort/{sample}.sorted.bam", sample=SAMPLES),
        bais=expand("030.sort/{sample}.sorted.bam.bai", sample=SAMPLES),
        ref="/lustre1/project/stg_00079/teaching/hg38_9/chr9.fa"
    output:
        "040.variants/combined.vcf"
    shell:
        """
        bcftools mpileup -f {input.ref} {input.bams} | bcftools call -mv -o {output}
        test -s {output}
        """

rule filter: 
    input:
        "040.variants/combined.vcf"
    output:
        "050.filter/combined.filtered.vcf"
    shell:
        """
        vt decompose {input} | vt normalize -r /lustre1/project/stg_00079/teaching/hg38_9/chr9.fa - | bcftools filter -i 'QUAL>20 && DP>10' -o {output}
        test -s {output}
        """

rule annotate: 
    input: 
        "050.filter/combined.filtered.vcf"
    output:
        vcf="060.annotate/combined.annotate.vcf",
        stats="060.annotate/snpEff_summary.html"
    shell:
        """
        snpEff -dataDir /lustre1/project/stg_00079/teaching/snpeff_db -stats {output.stats} hg38 {input} > {output.vcf}
        test -s {output.vcf}
        grep -q "ANN=" {output.vcf}
        """

rule to_tsv:
    input:
        "060.annotate/combined.annotate.vcf"
    output:
        "100.final/combined.snps.annotated.tsv"
    shell:
        """
        echo -e "CHROM\\tPOS\\tREF\\tALT\\tQUAL\\tTLE66_N_GT\\tTLE66_T_GT\\tANN" > {output}
        bcftools query -f '%CHROM\\t%POS\\t%REF\\t%ALT\\t%QUAL\\t[%GT\\t]%INFO/ANN\\n' {input} >> {output}
        test -s {output}
        grep -q "CHROM" {output}
        """

rule to_db:
    input:
        vcf="060.annotate/combined.annotate.vcf",
        script="scripts/vcf_to_sqlite.py"
    output:
        "150.db/snps.sqlite"
    shell:
        """
        python {input.script} {input.vcf} {output}
        test -s {output}

        echo "=== Test query 1: total SNP count ==="
        python -c "import sqlite3; print(sqlite3.connect('{output}').execute('SELECT COUNT(*) FROM SNP').fetchone()[0])"

        echo "=== Test query 2: orphan effects (must be 0) ==="
        python -c "import sqlite3; print(sqlite3.connect('{output}').execute('SELECT COUNT(*) FROM Effect WHERE snp_id NOT IN (SELECT snp_id FROM SNP)').fetchone()[0])"
        """
rule plot_snps:
    input:
        db="150.db/snps.sqlite",
        script="scripts/plot_snps.py"
    output:
        fig1="160.figures/fig1_impact_severity.svg",
        fig2="160.figures/fig2_top_genes.svg"
    shell:
        """
        python {input.script} {input.db} {output.fig1} {output.fig2}
        test -s {output.fig1}
        test -s {output.fig2}
        """